#删除为0的列
video_stats=video_stats[,-16]
video_stats=video_stats[,-18]
video_stats=video_stats[,-19]
video_stats=video_stats[,-25]
video_stats=video_stats[,-2]
video_stats1=as.data.frame(video_stats)
view(video_stats1)
p<-ggplot(video_stats1,aes(total_downloads))
bp4<-p+geom_density(color="red",fill="gray")
bp4
video_stats_1=video_stats1[1:13,]
class(video_stats_1)
library(reshape2)
dd=video_stats_1[,1:4]
p2<-ggplot(dd,aes(x=total_views,y=total_downloads,group=factor(1)))+geom_point(stat="identity",color=dd$step_position)
p2
dd2=video_stats_1[,9:14]
dd2
ggplot(dd2,aes(x=viewed_ten_percent,y=viewed_twentyfive_percent,group=factor(1)))+geom_boxplot()
ggplot(dd2,aes(x=viewed_ninetyfive_percent,y=viewed_onehundred_percent,group=factor(1)))+geom_boxplot()
#选取时间最长视频做分析
video_2.4=video_stats %>% filter(step_position == "2.4")
total_view=video_2.4[,4:7]
total_view4=as.data.frame(total_view)
view(total_view4)
#可视化
ggplot(total_view4,aes(y=total_downloads))+geom_density(color="green",fill="red")
ggplot(total_view4,aes(x=total_caption_views))+geom_density(color="black",fill="blue")
ggplot(total_view4,aes(x=otal_transcript_views))+geom_density(color="black",fill="gray")
ggplot(total_view4,aes(x=viewed_hd))+geom_density(color="black",fill="gray")

